### NumPy Revision

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
a[:2] # you are slicing up to the stopping index of 2 - format is i:j:k where i is starting, j stopping, k is step

array([1, 2])

In [5]:
a.shape 

(5,)

In [6]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
A = A.astype(int)

In [7]:
A.shape

(3, 4)

In [8]:
A[2,3] # single element indexing (2nd row 3rd col)

12

In [12]:
A[1:, 1:3] # multi element indexing - select all rows from index 1 onwards, select columns from 1 to 3 (2nd to 4th-not inclusive)


array([[ 6,  7],
       [10, 11]])

In [13]:
A[2,3] = 250 # setting new elements
A

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11, 250]])

In [14]:
I = np.eye(2) # creates a 2x2 identity array
I

array([[1., 0.],
       [0., 1.]])

In [16]:
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.zeros((5,5)) # creates an array of 0s with specified shape

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,4)) # creates an array of 1s with specified shape

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
C = np.full((5,5), np.nan) # creates an array with specified shape and fill_value (in this case np.nan)
C

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [19]:
X = np.random.random((100000,1)) # uniform distribution with 10,000 samples
print(X)

[[0.92731985]
 [0.75509351]
 [0.44419956]
 ...
 [0.81235095]
 [0.94652129]
 [0.89221622]]


In [24]:
print('Mean of X is approx:', np.mean(X)) # should be 0.5 
print('Stdev of X is approx:', np.std(X)**2) # should be close to 1/12

Mean of X is approx: 0.4991287677563973
Stdev of X is approx: 0.0833947739531488


* Arithmetic Operations

In [25]:
A = np.array([[1,5,6], [1,8,9], [1,-1,6]])
B = np.array([[4,8,4], [1,1,5], [6,-8,4]])

In [26]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 1, -1,  6]])

In [27]:
B

array([[ 4,  8,  4],
       [ 1,  1,  5],
       [ 6, -8,  4]])

In [33]:
C = np.add(A,B, dtype=float)
C

array([[ 5., 13., 10.],
       [ 2.,  9., 14.],
       [ 7., -9., 10.]])

In [34]:
C.dtype

dtype('float64')

In [35]:
D = np.subtract(A,B, dtype=float)
D

array([[-3., -3.,  2.],
       [ 0.,  7.,  4.],
       [-5.,  7.,  2.]])

In [36]:
E = np.multiply(A, B, dtype=float) # pointwise multiplication
E

array([[ 4., 40., 24.],
       [ 1.,  8., 45.],
       [ 6.,  8., 24.]])

In [37]:
F = np.divide(A, B, dtype=float) # pointwise division
F

array([[0.25      , 0.625     , 1.5       ],
       [1.        , 8.        , 1.8       ],
       [0.16666667, 0.125     , 1.5       ]])

In [39]:
F = np.int64(F)
F

array([[0, 0, 1],
       [1, 8, 1],
       [0, 0, 1]])

In [40]:
G = np.matmul(A, B, dtype=float) # matrix multiplcation
G

array([[ 45., -35.,  53.],
       [ 66., -56.,  80.],
       [ 39., -41.,  23.]])

In [41]:
a = A[:, 0]
b = B[:, 0]

a

array([1, 1, 1])

In [42]:
b

array([4, 1, 6])

In [43]:
np.matmul(a, b) # 4+1+6

11

recall in linear algebra dot product is represented as $ x\cdot y \text{ becomes } \textbf{x}^T \textbf{y}.$


In [44]:
np.dot(a, b) # dot product, product of 2 same size vectors; returns scalar

11

In [45]:
np.inner(a, b) # inner product, 

11

In [46]:
np.matmul(A, A) # matrix multiplication of A with itself

array([[ 12,  39,  87],
       [ 18,  60, 132],
       [  6,  -9,  33]])

In [47]:
np.linalg.matrix_power(A, 2) # matrix power 2 

array([[ 12,  39,  87],
       [ 18,  60, 132],
       [  6,  -9,  33]])

* Matrix Decomposition

**QR Decomposition**

$$ A = QR $$
where Q is an orthonormal matrix and R is an upper triangular matrix. 

In [48]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 1, -1,  6]])

In [49]:
Q, R = np.linalg.qr(A)

In [50]:
Q

array([[-0.57735027, -0.15430335, -0.80178373],
       [-0.57735027, -0.6172134 ,  0.53452248],
       [-0.57735027,  0.77151675,  0.26726124]])

In [51]:
R

array([[ -1.73205081,  -6.92820323, -12.12435565],
       [  0.        ,  -6.4807407 ,  -1.8516402 ],
       [  0.        ,   0.        ,   1.60356745]])

In [52]:
np.matmul(Q, R)

array([[ 1.,  5.,  6.],
       [ 1.,  8.,  9.],
       [ 1., -1.,  6.]])

**Eigenvalue Decomposition**

$$ A = PDP^{-1} $$
where P's columns consists of the eigenvectors of A and D is a diagonal matrix whose entries are the eigenvalues of A.

In [53]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 1, -1,  6]])

In [58]:
d, P = np.linalg.eig(A)

In [59]:
d

array([0.32598999+0.j        , 7.33700501+1.17676556j,
       7.33700501-1.17676556j])

In [60]:
P

array([[-0.98472698+0.j        ,  0.53851429+0.00214369j,
         0.53851429-0.00214369j],
       [-0.06233426+0.j        ,  0.82690915+0.j        ,
         0.82690915-0.j        ],
       [ 0.16256452+0.j        , -0.1207501 +0.10788161j,
        -0.1207501 -0.10788161j]])

In [61]:
D = np.diag(d) # extract a diagonal array
D

array([[0.32598999+0.j        , 0.        +0.j        ,
        0.        +0.j        ],
       [0.        +0.j        , 7.33700501+1.17676556j,
        0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        7.33700501-1.17676556j]])

In [62]:
np.real(np.matmul(np.matmul(P, D), np.linalg.inv(P)))

array([[ 1.,  5.,  6.],
       [ 1.,  8.,  9.],
       [ 1., -1.,  6.]])

**Singular Value Decomposition**

$$ A = USV^{T} $$

where the equation represents the decomposition of a matrix $A$ into three matrices: $U$, $S$, and $V^{T}$.

$A$ is an $m \times n$ matrix that we want to decompose using SVD.
$U$ is an $m \times m$ orthogonal matrix, which means that its columns are orthonormal vectors (unit vectors that are orthogonal to each other). The columns of $U$ are called the left singular vectors of $A$.
$S$ is an $m \times n$ diagonal matrix with non-negative real numbers on the diagonal. These diagonal entries are known as the singular values of $A$ and are typically arranged in descending order. The singular values represent the scaling factors applied to the singular vectors.
$V^{T}$ is the transpose of an $n \times n$ orthogonal matrix $V$. The columns of $V$ are called the right singular vectors of $A$.

In [63]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 1, -1,  6]])

In [64]:
U, s, V_t = np.linalg.svd(A)
S = np.diag(s)

np.matmul(np.matmul(U, S), V_t)

array([[ 1.,  5.,  6.],
       [ 1.,  8.,  9.],
       [ 1., -1.,  6.]])

* Matrix Norms

In [65]:
np.linalg.norm(A) # default norm for vectors 2-norm

15.684387141358123

In [66]:
np.linalg.det(A) # compute the determinant of an array

17.999999999999996

In [67]:
np.linalg.matrix_rank(A) # return matrix rank of array using SVD method

3

In [68]:
np.trace(A) # return sum along diagonals of the array

15

* Solving Equations

$$ Ax = b $$

In [69]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 1, -1,  6]])

In [70]:
b = np.random.random((3,1))
b

array([[0.35555247],
       [0.97543415],
       [0.1037853 ]])

In [71]:
np.linalg.solve(A, b)

array([[-0.84224969],
       [ 0.0419612 ],
       [ 0.16466603]])

alternatively:

$$ \text{taking inverse A on both sides:} \ A^{-1}Ax = A^{-1}b $$

the matrix multiplied by its inverse equates to 1

In [73]:
np.matmul(np.linalg.inv(A), b)

array([[-0.84224969],
       [ 0.0419612 ],
       [ 0.16466603]])